package sdkcodegen

import (
	"fmt"
	"strings"
)

func (g *Generator) generateJava(schema *SchemaDefinition) (string, string, error) {
	var b strings.Builder
	className := toPascalCase(schema.Name)
	fileName := className + ".java"

	b.WriteString("// Code generated by feather sdkcodegen. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("// Source: %s (version %s)\n\n", schema.Name, schema.Version))
	b.WriteString(fmt.Sprintf("package %s;\n\n", g.config.PackageName))
	b.WriteString("import com.fasterxml.jackson.annotation.JsonProperty;\n")
	b.WriteString("import java.time.Instant;\n")
	b.WriteString("import java.util.List;\n\n")

	// Class
	if schema.Description != "" {
		b.WriteString(fmt.Sprintf("/**\n * %s\n */\n", schema.Description))
	}
	b.WriteString(fmt.Sprintf("public class %s {\n\n", className))

	// Fields
	b.WriteString("    @JsonProperty(\"entity_id\")\n")
	b.WriteString("    private String entityId;\n\n")
	b.WriteString("    @JsonProperty(\"timestamp\")\n")
	b.WriteString("    private Instant timestamp;\n\n")
	for _, f := range schema.Fields {
		javaType := javaTypeFor(f.Type)
		b.WriteString(fmt.Sprintf("    @JsonProperty(\"%s\")\n", f.Name))
		b.WriteString(fmt.Sprintf("    private %s %s;\n\n", javaType, toCamelCase(f.Name)))
	}

	// Default constructor
	b.WriteString(fmt.Sprintf("    public %s() {}\n\n", className))

	// Getters and setters
	b.WriteString("    public String getEntityId() { return entityId; }\n")
	b.WriteString("    public void setEntityId(String entityId) { this.entityId = entityId; }\n\n")
	b.WriteString("    public Instant getTimestamp() { return timestamp; }\n")
	b.WriteString("    public void setTimestamp(Instant timestamp) { this.timestamp = timestamp; }\n\n")
	for _, f := range schema.Fields {
		javaType := javaTypeFor(f.Type)
		camel := toCamelCase(f.Name)
		pascal := toPascalCase(f.Name)
		b.WriteString(fmt.Sprintf("    public %s get%s() { return %s; }\n", javaType, pascal, camel))
		b.WriteString(fmt.Sprintf("    public void set%s(%s %s) { this.%s = %s; }\n\n", pascal, javaType, camel, camel, camel))
	}

	// Builder
	b.WriteString("    public static Builder builder() { return new Builder(); }\n\n")
	b.WriteString("    public static class Builder {\n")
	b.WriteString(fmt.Sprintf("        private final %s instance = new %s();\n\n", className, className))
	b.WriteString("        public Builder entityId(String entityId) { instance.entityId = entityId; return this; }\n")
	b.WriteString("        public Builder timestamp(Instant timestamp) { instance.timestamp = timestamp; return this; }\n")
	for _, f := range schema.Fields {
		javaType := javaTypeFor(f.Type)
		camel := toCamelCase(f.Name)
		b.WriteString(fmt.Sprintf("        public Builder %s(%s %s) { instance.%s = %s; return this; }\n", camel, javaType, camel, camel, camel))
	}
	b.WriteString(fmt.Sprintf("\n        public %s build() { return instance; }\n", className))
	b.WriteString("    }\n")

	b.WriteString("}\n")

	return b.String(), fileName, nil
}

func javaTypeFor(ft FieldType) string {
	switch ft {
	case FieldInt64:
		return "Long"
	case FieldFloat64:
		return "Double"
	case FieldString:
		return "String"
	case FieldBool:
		return "Boolean"
	case FieldBytes:
		return "byte[]"
	case FieldVector:
		return "List<Double>"
	case FieldTimestamp:
		return "Instant"
	default:
		return "Object"
	}
}

func toCamelCase(s string) string {
	pascal := toPascalCase(s)
	if len(pascal) == 0 {
		return ""
	}
	return strings.ToLower(pascal[:1]) + pascal[1:]
}
