package sdkcodegen

import (
	"fmt"
	"strings"
)

func (g *Generator) generateKotlin(schema *SchemaDefinition) (string, string, error) {
	var b strings.Builder
	className := toPascalCase(schema.Name)
	fileName := className + ".kt"

	b.WriteString("// Code generated by feather sdkcodegen. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("// Source: %s (version %s)\n\n", schema.Name, schema.Version))
	b.WriteString(fmt.Sprintf("package %s\n\n", g.config.PackageName))
	b.WriteString("import kotlinx.serialization.SerialName\n")
	b.WriteString("import kotlinx.serialization.Serializable\n")
	b.WriteString("import java.time.Instant\n\n")

	// Data class
	if schema.Description != "" {
		b.WriteString(fmt.Sprintf("/**\n * %s\n */\n", schema.Description))
	}
	b.WriteString("@Serializable\n")
	b.WriteString(fmt.Sprintf("data class %s(\n", className))
	b.WriteString("    @SerialName(\"entity_id\")\n")
	b.WriteString("    val entityId: String,\n\n")
	b.WriteString("    @SerialName(\"timestamp\")\n")
	b.WriteString("    val timestamp: String = Instant.now().toString(),\n\n")
	for i, f := range schema.Fields {
		kotlinType := kotlinTypeFor(f.Type)
		camel := toCamelCase(f.Name)
		sep := ","
		if i == len(schema.Fields)-1 {
			sep = ""
		}
		if camel != f.Name {
			b.WriteString(fmt.Sprintf("    @SerialName(\"%s\")\n", f.Name))
		}
		if !f.Required {
			b.WriteString(fmt.Sprintf("    val %s: %s? = null%s\n", camel, kotlinType, sep))
		} else {
			b.WriteString(fmt.Sprintf("    val %s: %s%s\n", camel, kotlinType, sep))
		}
		if i < len(schema.Fields)-1 {
			b.WriteString("\n")
		}
	}
	b.WriteString(")\n")

	return b.String(), fileName, nil
}

func kotlinTypeFor(ft FieldType) string {
	switch ft {
	case FieldInt64:
		return "Long"
	case FieldFloat64:
		return "Double"
	case FieldString:
		return "String"
	case FieldBool:
		return "Boolean"
	case FieldBytes:
		return "ByteArray"
	case FieldVector:
		return "List<Double>"
	case FieldTimestamp:
		return "String"
	default:
		return "Any"
	}
}
