package sdkcodegen

import (
	"fmt"
	"strings"
)

func (g *Generator) generateRust(schema *SchemaDefinition) (string, string, error) {
	var b strings.Builder
	structName := toPascalCase(schema.Name)
	fileName := toSnakeCase(schema.Name) + ".rs"

	b.WriteString("// Code generated by feather sdkcodegen. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("// Source: %s (version %s)\n\n", schema.Name, schema.Version))
	b.WriteString("use serde::{Deserialize, Serialize};\n")
	b.WriteString("use chrono::{DateTime, Utc};\n\n")

	// Struct
	if schema.Description != "" {
		b.WriteString(fmt.Sprintf("/// %s\n", schema.Description))
	}
	b.WriteString("#[derive(Debug, Clone, Serialize, Deserialize)]\n")
	b.WriteString(fmt.Sprintf("pub struct %s {\n", structName))
	b.WriteString("    pub entity_id: String,\n")
	b.WriteString("    pub timestamp: DateTime<Utc>,\n")
	for _, f := range schema.Fields {
		rustType := rustTypeFor(f.Type)
		if !f.Required {
			rustType = fmt.Sprintf("Option<%s>", rustType)
		}
		b.WriteString(fmt.Sprintf("    pub %s: %s,\n", f.Name, rustType))
	}
	b.WriteString("}\n\n")

	// Builder
	b.WriteString(fmt.Sprintf("pub struct %sBuilder {\n", structName))
	b.WriteString("    entity_id: Option<String>,\n")
	b.WriteString("    timestamp: Option<DateTime<Utc>>,\n")
	for _, f := range schema.Fields {
		rustType := rustTypeFor(f.Type)
		b.WriteString(fmt.Sprintf("    %s: Option<%s>,\n", f.Name, rustType))
	}
	b.WriteString("}\n\n")

	b.WriteString(fmt.Sprintf("impl %s {\n", structName))
	b.WriteString(fmt.Sprintf("    pub fn builder() -> %sBuilder {\n", structName))
	b.WriteString(fmt.Sprintf("        %sBuilder {\n", structName))
	b.WriteString("            entity_id: None,\n")
	b.WriteString("            timestamp: None,\n")
	for _, f := range schema.Fields {
		b.WriteString(fmt.Sprintf("            %s: None,\n", f.Name))
	}
	b.WriteString("        }\n")
	b.WriteString("    }\n")
	b.WriteString("}\n\n")

	b.WriteString(fmt.Sprintf("impl %sBuilder {\n", structName))
	b.WriteString("    pub fn entity_id(mut self, val: String) -> Self { self.entity_id = Some(val); self }\n")
	b.WriteString("    pub fn timestamp(mut self, val: DateTime<Utc>) -> Self { self.timestamp = Some(val); self }\n")
	for _, f := range schema.Fields {
		rustType := rustTypeFor(f.Type)
		b.WriteString(fmt.Sprintf("    pub fn %s(mut self, val: %s) -> Self { self.%s = Some(val); self }\n", f.Name, rustType, f.Name))
	}
	b.WriteString(fmt.Sprintf("\n    pub fn build(self) -> Result<%s, &'static str> {\n", structName))
	b.WriteString(fmt.Sprintf("        Ok(%s {\n", structName))
	b.WriteString("            entity_id: self.entity_id.ok_or(\"entity_id is required\")?,\n")
	b.WriteString("            timestamp: self.timestamp.unwrap_or_else(Utc::now),\n")
	for _, f := range schema.Fields {
		if f.Required {
			b.WriteString(fmt.Sprintf("            %s: self.%s.ok_or(\"%s is required\")?,\n", f.Name, f.Name, f.Name))
		} else {
			b.WriteString(fmt.Sprintf("            %s: self.%s,\n", f.Name, f.Name))
		}
	}
	b.WriteString("        })\n")
	b.WriteString("    }\n")
	b.WriteString("}\n")

	return b.String(), fileName, nil
}

func rustTypeFor(ft FieldType) string {
	switch ft {
	case FieldInt64:
		return "i64"
	case FieldFloat64:
		return "f64"
	case FieldString:
		return "String"
	case FieldBool:
		return "bool"
	case FieldBytes:
		return "Vec<u8>"
	case FieldVector:
		return "Vec<f64>"
	case FieldTimestamp:
		return "DateTime<Utc>"
	default:
		return "serde_json::Value"
	}
}
