package sdkcodegen

import (
	"fmt"
	"strings"
)

func (g *Generator) generateSwift(schema *SchemaDefinition) (string, string, error) {
	var b strings.Builder
	structName := toPascalCase(schema.Name)
	fileName := structName + ".swift"

	b.WriteString("// Code generated by feather sdkcodegen. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("// Source: %s (version %s)\n\n", schema.Name, schema.Version))
	b.WriteString("import Foundation\n\n")

	// Struct with Codable conformance
	if schema.Description != "" {
		b.WriteString(fmt.Sprintf("/// %s\n", schema.Description))
	}
	b.WriteString(fmt.Sprintf("public struct %s: Codable {\n", structName))
	b.WriteString("    public let entityId: String\n")
	b.WriteString("    public let timestamp: Date\n")
	for _, f := range schema.Fields {
		swiftType := swiftTypeFor(f.Type)
		if !f.Required {
			swiftType += "?"
		}
		b.WriteString(fmt.Sprintf("    public let %s: %s\n", toCamelCase(f.Name), swiftType))
	}
	b.WriteString("\n")

	// CodingKeys
	b.WriteString("    enum CodingKeys: String, CodingKey {\n")
	b.WriteString("        case entityId = \"entity_id\"\n")
	b.WriteString("        case timestamp\n")
	for _, f := range schema.Fields {
		camel := toCamelCase(f.Name)
		if camel != f.Name {
			b.WriteString(fmt.Sprintf("        case %s = \"%s\"\n", camel, f.Name))
		} else {
			b.WriteString(fmt.Sprintf("        case %s\n", camel))
		}
	}
	b.WriteString("    }\n\n")

	// Init
	b.WriteString("    public init(\n")
	b.WriteString("        entityId: String,\n")
	b.WriteString("        timestamp: Date = Date(),\n")
	for i, f := range schema.Fields {
		swiftType := swiftTypeFor(f.Type)
		camel := toCamelCase(f.Name)
		sep := ","
		if i == len(schema.Fields)-1 {
			sep = ""
		}
		if !f.Required {
			b.WriteString(fmt.Sprintf("        %s: %s? = nil%s\n", camel, swiftType, sep))
		} else {
			b.WriteString(fmt.Sprintf("        %s: %s%s\n", camel, swiftType, sep))
		}
	}
	b.WriteString("    ) {\n")
	b.WriteString("        self.entityId = entityId\n")
	b.WriteString("        self.timestamp = timestamp\n")
	for _, f := range schema.Fields {
		camel := toCamelCase(f.Name)
		b.WriteString(fmt.Sprintf("        self.%s = %s\n", camel, camel))
	}
	b.WriteString("    }\n")

	b.WriteString("}\n")

	return b.String(), fileName, nil
}

func swiftTypeFor(ft FieldType) string {
	switch ft {
	case FieldInt64:
		return "Int64"
	case FieldFloat64:
		return "Double"
	case FieldString:
		return "String"
	case FieldBool:
		return "Bool"
	case FieldBytes:
		return "Data"
	case FieldVector:
		return "[Double]"
	case FieldTimestamp:
		return "Date"
	default:
		return "Any"
	}
}
