package main

import "github.com/feather-store/feather/internal/core/config"

// buildEnabledFeatures returns the feature enablement map based on configuration.
func buildEnabledFeatures(cfg *config.Config) map[string]bool {
	return map[string]bool{
		"groups":          true,
		"backfill":        true,
		"streaming":       true,
		"catalog":         true,
		"auth":            true,
		"ml":              true,
		"transform":       true,
		"cache":           true,
		"consistency":     true,
		"impact":          true,
		"observability":   true,
		"benchmark":       true,
		"joins":           true,
		"lineage":         true,
		"contracts":       true,
		"llm_cache":       true,
		"materialization": true,
		"parity":          true,
		"replication":     true,
		"playground":      true,
		"mesh":            true,
		"pipelines":       true,
		"multimodal":      true,
		"costopt":         true,
		"active_active":   true,
		"ftl":             true,
		"billing":         true,
		"quality_score":   true,
		"orchestrator":    true,
		"mobile_sync":     true,
		"explorer":        true,
		"ui":              cfg.UI.Enabled,
		"dbt":             cfg.DBT.Enabled,
		"ml_integrations": true,
		"smpc":            true,
		// Next-gen features
		"stream_compute":        true,
		"sdk_codegen":           true,
		"prompt_store":          true,
		"consistency_validator": true,
		"feature_dashboard":     true,
		"featherql_v2":          true,
		"embedding_mgmt":        true,
		"schema_evolution":      true,
		"feast_compat":          true,
		"saas_control":          true,
		// Next-gen v2 features
		"lineage_graph":       true,
		"adaptive_cache":      true,
		"contract_test":       true,
		"backpressure":        true,
		"offline_store":       true,
		"bench_pub":           true,
		"gitops_defs":         true,
		"ab_features":         true,
		"federated_discovery": true,
		"wasm_udf":            true,
		// Next-gen v3 features
		"api_gateway":          true,
		"importance_scoring":   true,
		"anomaly_detect":       true,
		"feather_cli":          true,
		"incr_materialization": true,
		"webhook_events":       true,
		"cloud_storage":        true,
		"audit_log":            true,
		"openapi_sync":         true,
		"terraform_provider":   true,
		"flink_pipeline":       true,
		"feast_gateway":        true,
		"cloud_control":        true,
		"realtime_monitor":     true,
		"cdc_materialization":  true,
		"python_transforms":    true,
		"region_federation":    true,
		"lineage_analysis":     true,
		"wasm_runtime":         true,
		"llm_store":            true,
		"model_registry":       true,
		"nl_discovery":         true,
		// Next-gen v4 features
		"arrow_flight":  true,
		"diff_privacy":  true,
		"prefetch":      true,
		"notebook_sdk":  true,
		"quality_gates": true,
		"compression":   true,
		"audit_trail":   true,
		"query_planner": true,
		"fed_learning":  true,
		"playground_v2": true,
		// Next-gen v5 features
		"starlark_udf":          true,
		"model_gateway":         true,
		"semantic_catalog":      true,
		"federation_cross_org":  true,
		"lifecycle_manager":     true,
		// Next-gen v6 features
		"python_runtime":        true,
		"compute_graph_v2":      true,
		"consistency_advanced":  true,
		"gitops_manifests":      true,
		"arrow_batch":           true,
		"stream_advanced":       true,
		"feast_enhanced":        true,
		"embedding_lifecycle":   true,
		"sdk_languages":         true,
		"predictive_warming":    true,
		// Next-gen v7 features
		"backfill_engine":       true,
		"contract_cicd":         true,
		"flight_endpoint":       true,
		"declarative_graph":     true,
		"multi_tenant_metering": true,
		"python_sidecar":        true,
		"obs_console":           true,
		"auto_sharding":         true,
		"feast_ga":              true,
		"offline_store_sync":    true,
	}
}
