// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.7
// source: api/proto/feather.proto

package featherpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServingStatus represents the health status.
type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN         HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING         HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING     HealthCheckResponse_ServingStatus = 2
	HealthCheckResponse_SERVICE_UNKNOWN HealthCheckResponse_ServingStatus = 3
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
		3: "SERVICE_UNKNOWN",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":         0,
		"SERVING":         1,
		"NOT_SERVING":     2,
		"SERVICE_UNKNOWN": 3,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_feather_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_api_proto_feather_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_feather_proto_rawDescGZIP(), []int{10, 0}
}

// GetFeaturesRequest is the request to get features.
type GetFeaturesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Entity keys to retrieve features for.
	Entities []string `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	// Feature names to retrieve.
	Features      []string `protobuf:"bytes,2,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeaturesRequest) Reset() {
	*x = GetFeaturesRequest{}
	mi := &file_api_proto_feather_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeaturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeaturesRequest) ProtoMessage() {}

func (x *GetFeaturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feather_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeaturesRequest.ProtoReflect.Descriptor instead.
func (*GetFeaturesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_feather_proto_rawDescGZIP(), []int{0}
}

func (x *GetFeaturesRequest) GetEntities() []string {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *GetFeaturesRequest) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

// GetFeaturesAsOfRequest retrieves historical features.
type GetFeaturesAsOfRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Entity key to retrieve features for.
	EntityKey string `protobuf:"bytes,1,opt,name=entity_key,json=entityKey,proto3" json:"entity_key,omitempty"`
	// Feature names to retrieve.
	Features []string `protobuf:"bytes,2,rep,name=features,proto3" json:"features,omitempty"`
	// Timestamp to retrieve features as of (Unix nanoseconds).
	AsOfTimestamp int64 `protobuf:"varint,3,opt,name=as_of_timestamp,json=asOfTimestamp,proto3" json:"as_of_timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeaturesAsOfRequest) Reset() {
	*x = GetFeaturesAsOfRequest{}
	mi := &file_api_proto_feather_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeaturesAsOfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeaturesAsOfRequest) ProtoMessage() {}

func (x *GetFeaturesAsOfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feather_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeaturesAsOfRequest.ProtoReflect.Descriptor instead.
func (*GetFeaturesAsOfRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_feather_proto_rawDescGZIP(), []int{1}
}

func (x *GetFeaturesAsOfRequest) GetEntityKey() string {
	if x != nil {
		return x.EntityKey
	}
	return ""
}

func (x *GetFeaturesAsOfRequest) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *GetFeaturesAsOfRequest) GetAsOfTimestamp() int64 {
	if x != nil {
		return x.AsOfTimestamp
	}
	return 0
}

// GetFeaturesResponse is the response containing features.
type GetFeaturesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Features by entity key.
	Entities      map[string]*EntityFeatures `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeaturesResponse) Reset() {
	*x = GetFeaturesResponse{}
	mi := &file_api_proto_feather_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeaturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeaturesResponse) ProtoMessage() {}

func (x *GetFeaturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feather_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeaturesResponse.ProtoReflect.Descriptor instead.
func (*GetFeaturesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_feather_proto_rawDescGZIP(), []int{2}
}

func (x *GetFeaturesResponse) GetEntities() map[string]*EntityFeatures {
	if x != nil {
		return x.Entities
	}
	return nil
}

// EntityFeaturesResponse is a streaming response for a single entity.
type EntityFeaturesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Entity key.
	EntityKey string `protobuf:"bytes,1,opt,name=entity_key,json=entityKey,proto3" json:"entity_key,omitempty"`
	// Features for this entity.
	Features      *EntityFeatures `protobuf:"bytes,2,opt,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityFeaturesResponse) Reset() {
	*x = EntityFeaturesResponse{}
	mi := &file_api_proto_feather_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityFeaturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityFeaturesResponse) ProtoMessage() {}

func (x *EntityFeaturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feather_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityFeaturesResponse.ProtoReflect.Descriptor instead.
func (*EntityFeaturesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_feather_proto_rawDescGZIP(), []int{3}
}

func (x *EntityFeaturesResponse) GetEntityKey() string {
	if x != nil {
		return x.EntityKey
	}
	return ""
}

func (x *EntityFeaturesResponse) GetFeatures() *EntityFeatures {
	if x != nil {
		return x.Features
	}
	return nil
}

// EntityFeatures contains all features for an entity.
type EntityFeatures struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Features by name.
	Features      map[string]*FeatureValue `protobuf:"bytes,1,rep,name=features,proto3" json:"features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityFeatures) Reset() {
	*x = EntityFeatures{}
	mi := &file_api_proto_feather_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityFeatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityFeatures) ProtoMessage() {}

func (x *EntityFeatures) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feather_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityFeatures.ProtoReflect.Descriptor instead.
func (*EntityFeatures) Descriptor() ([]byte, []int) {
	return file_api_proto_feather_proto_rawDescGZIP(), []int{4}
}

func (x *EntityFeatures) GetFeatures() map[string]*FeatureValue {
	if x != nil {
		return x.Features
	}
	return nil
}

// FeatureValue represents a single feature value.
type FeatureValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The value, stored as one of these types.
	//
	// Types that are valid to be assigned to Value:
	//
	//	*FeatureValue_IntValue
	//	*FeatureValue_DoubleValue
	//	*FeatureValue_StringValue
	//	*FeatureValue_BoolValue
	//	*FeatureValue_BytesValue
	//	*FeatureValue_VectorValue
	Value isFeatureValue_Value `protobuf_oneof:"value"`
	// Timestamp when this value was set (Unix nanoseconds).
	Timestamp     int64 `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureValue) Reset() {
	*x = FeatureValue{}
	mi := &file_api_proto_feather_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureValue) ProtoMessage() {}

func (x *FeatureValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feather_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureValue.ProtoReflect.Descriptor instead.
func (*FeatureValue) Descriptor() ([]byte, []int) {
	return file_api_proto_feather_proto_rawDescGZIP(), []int{5}
}

func (x *FeatureValue) GetValue() isFeatureValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *FeatureValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*FeatureValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *FeatureValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*FeatureValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *FeatureValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*FeatureValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *FeatureValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*FeatureValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *FeatureValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*FeatureValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *FeatureValue) GetVectorValue() *VectorValue {
	if x != nil {
		if x, ok := x.Value.(*FeatureValue_VectorValue); ok {
			return x.VectorValue
		}
	}
	return nil
}

func (x *FeatureValue) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type isFeatureValue_Value interface {
	isFeatureValue_Value()
}

type FeatureValue_IntValue struct {
	IntValue int64 `protobuf:"varint,1,opt,name=int_value,json=intValue,proto3,oneof"`
}

type FeatureValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,2,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type FeatureValue_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type FeatureValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type FeatureValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,5,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type FeatureValue_VectorValue struct {
	VectorValue *VectorValue `protobuf:"bytes,6,opt,name=vector_value,json=vectorValue,proto3,oneof"`
}

func (*FeatureValue_IntValue) isFeatureValue_Value() {}

func (*FeatureValue_DoubleValue) isFeatureValue_Value() {}

func (*FeatureValue_StringValue) isFeatureValue_Value() {}

func (*FeatureValue_BoolValue) isFeatureValue_Value() {}

func (*FeatureValue_BytesValue) isFeatureValue_Value() {}

func (*FeatureValue_VectorValue) isFeatureValue_Value() {}

// VectorValue represents a float32 array.
type VectorValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorValue) Reset() {
	*x = VectorValue{}
	mi := &file_api_proto_feather_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorValue) ProtoMessage() {}

func (x *VectorValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feather_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorValue.ProtoReflect.Descriptor instead.
func (*VectorValue) Descriptor() ([]byte, []int) {
	return file_api_proto_feather_proto_rawDescGZIP(), []int{6}
}

func (x *VectorValue) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

// PutFeaturesRequest stores features for an entity.
type PutFeaturesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Entity key.
	EntityKey string `protobuf:"bytes,1,opt,name=entity_key,json=entityKey,proto3" json:"entity_key,omitempty"`
	// Features to store.
	Features map[string]*FeatureValue `protobuf:"bytes,2,rep,name=features,proto3" json:"features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Version for conflict resolution (optional).
	Version       int64 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutFeaturesRequest) Reset() {
	*x = PutFeaturesRequest{}
	mi := &file_api_proto_feather_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutFeaturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFeaturesRequest) ProtoMessage() {}

func (x *PutFeaturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feather_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFeaturesRequest.ProtoReflect.Descriptor instead.
func (*PutFeaturesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_feather_proto_rawDescGZIP(), []int{7}
}

func (x *PutFeaturesRequest) GetEntityKey() string {
	if x != nil {
		return x.EntityKey
	}
	return ""
}

func (x *PutFeaturesRequest) GetFeatures() map[string]*FeatureValue {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *PutFeaturesRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// PutFeaturesResponse is the response after storing features.
type PutFeaturesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the operation succeeded.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if failed.
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutFeaturesResponse) Reset() {
	*x = PutFeaturesResponse{}
	mi := &file_api_proto_feather_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutFeaturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFeaturesResponse) ProtoMessage() {}

func (x *PutFeaturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feather_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFeaturesResponse.ProtoReflect.Descriptor instead.
func (*PutFeaturesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_feather_proto_rawDescGZIP(), []int{8}
}

func (x *PutFeaturesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PutFeaturesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// HealthCheckRequest is the request for health checking.
type HealthCheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service name to check. Empty string checks overall health.
	Service       string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_feather_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feather_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_feather_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// HealthCheckResponse is the response for health checking.
type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=feather.v1.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_feather_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feather_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_feather_proto_rawDescGZIP(), []int{10}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

var File_api_proto_feather_proto protoreflect.FileDescriptor

const file_api_proto_feather_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/feather.proto\x12\n" +
	"feather.v1\"L\n" +
	"\x12GetFeaturesRequest\x12\x1a\n" +
	"\bentities\x18\x01 \x03(\tR\bentities\x12\x1a\n" +
	"\bfeatures\x18\x02 \x03(\tR\bfeatures\"{\n" +
	"\x16GetFeaturesAsOfRequest\x12\x1d\n" +
	"\n" +
	"entity_key\x18\x01 \x01(\tR\tentityKey\x12\x1a\n" +
	"\bfeatures\x18\x02 \x03(\tR\bfeatures\x12&\n" +
	"\x0fas_of_timestamp\x18\x03 \x01(\x03R\rasOfTimestamp\"\xb9\x01\n" +
	"\x13GetFeaturesResponse\x12I\n" +
	"\bentities\x18\x01 \x03(\v2-.feather.v1.GetFeaturesResponse.EntitiesEntryR\bentities\x1aW\n" +
	"\rEntitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.feather.v1.EntityFeaturesR\x05value:\x028\x01\"o\n" +
	"\x16EntityFeaturesResponse\x12\x1d\n" +
	"\n" +
	"entity_key\x18\x01 \x01(\tR\tentityKey\x126\n" +
	"\bfeatures\x18\x02 \x01(\v2\x1a.feather.v1.EntityFeaturesR\bfeatures\"\xad\x01\n" +
	"\x0eEntityFeatures\x12D\n" +
	"\bfeatures\x18\x01 \x03(\v2(.feather.v1.EntityFeatures.FeaturesEntryR\bfeatures\x1aU\n" +
	"\rFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.feather.v1.FeatureValueR\x05value:\x028\x01\"\xa0\x02\n" +
	"\fFeatureValue\x12\x1d\n" +
	"\tint_value\x18\x01 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x02 \x01(\x01H\x00R\vdoubleValue\x12#\n" +
	"\fstring_value\x18\x03 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vbytes_value\x18\x05 \x01(\fH\x00R\n" +
	"bytesValue\x12<\n" +
	"\fvector_value\x18\x06 \x01(\v2\x17.feather.v1.VectorValueH\x00R\vvectorValue\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x03R\ttimestampB\a\n" +
	"\x05value\"%\n" +
	"\vVectorValue\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"\xee\x01\n" +
	"\x12PutFeaturesRequest\x12\x1d\n" +
	"\n" +
	"entity_key\x18\x01 \x01(\tR\tentityKey\x12H\n" +
	"\bfeatures\x18\x02 \x03(\v2,.feather.v1.PutFeaturesRequest.FeaturesEntryR\bfeatures\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x1aU\n" +
	"\rFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.feather.v1.FeatureValueR\x05value:\x028\x01\"E\n" +
	"\x13PutFeaturesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xad\x01\n" +
	"\x13HealthCheckResponse\x12E\n" +
	"\x06status\x18\x01 \x01(\x0e2-.feather.v1.HealthCheckResponse.ServingStatusR\x06status\"O\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\x12\x13\n" +
	"\x0fSERVICE_UNKNOWN\x10\x032\xe3\x02\n" +
	"\x0eFeatureService\x12N\n" +
	"\vGetFeatures\x12\x1e.feather.v1.GetFeaturesRequest\x1a\x1f.feather.v1.GetFeaturesResponse\x12Y\n" +
	"\x11GetFeaturesStream\x12\x1e.feather.v1.GetFeaturesRequest\x1a\".feather.v1.EntityFeaturesResponse0\x01\x12V\n" +
	"\x0fGetFeaturesAsOf\x12\".feather.v1.GetFeaturesAsOfRequest\x1a\x1f.feather.v1.GetFeaturesResponse\x12N\n" +
	"\vPutFeatures\x12\x1e.feather.v1.PutFeaturesRequest\x1a\x1f.feather.v1.PutFeaturesResponse2\x9e\x01\n" +
	"\x06Health\x12H\n" +
	"\x05Check\x12\x1e.feather.v1.HealthCheckRequest\x1a\x1f.feather.v1.HealthCheckResponse\x12J\n" +
	"\x05Watch\x12\x1e.feather.v1.HealthCheckRequest\x1a\x1f.feather.v1.HealthCheckResponse0\x01B0Z.github.com/feather-store/feather/api/featherpbb\x06proto3"

var (
	file_api_proto_feather_proto_rawDescOnce sync.Once
	file_api_proto_feather_proto_rawDescData []byte
)

func file_api_proto_feather_proto_rawDescGZIP() []byte {
	file_api_proto_feather_proto_rawDescOnce.Do(func() {
		file_api_proto_feather_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_feather_proto_rawDesc), len(file_api_proto_feather_proto_rawDesc)))
	})
	return file_api_proto_feather_proto_rawDescData
}

var file_api_proto_feather_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_feather_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_feather_proto_goTypes = []any{
	(HealthCheckResponse_ServingStatus)(0), // 0: feather.v1.HealthCheckResponse.ServingStatus
	(*GetFeaturesRequest)(nil),             // 1: feather.v1.GetFeaturesRequest
	(*GetFeaturesAsOfRequest)(nil),         // 2: feather.v1.GetFeaturesAsOfRequest
	(*GetFeaturesResponse)(nil),            // 3: feather.v1.GetFeaturesResponse
	(*EntityFeaturesResponse)(nil),         // 4: feather.v1.EntityFeaturesResponse
	(*EntityFeatures)(nil),                 // 5: feather.v1.EntityFeatures
	(*FeatureValue)(nil),                   // 6: feather.v1.FeatureValue
	(*VectorValue)(nil),                    // 7: feather.v1.VectorValue
	(*PutFeaturesRequest)(nil),             // 8: feather.v1.PutFeaturesRequest
	(*PutFeaturesResponse)(nil),            // 9: feather.v1.PutFeaturesResponse
	(*HealthCheckRequest)(nil),             // 10: feather.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 11: feather.v1.HealthCheckResponse
	nil,                                    // 12: feather.v1.GetFeaturesResponse.EntitiesEntry
	nil,                                    // 13: feather.v1.EntityFeatures.FeaturesEntry
	nil,                                    // 14: feather.v1.PutFeaturesRequest.FeaturesEntry
}
var file_api_proto_feather_proto_depIdxs = []int32{
	12, // 0: feather.v1.GetFeaturesResponse.entities:type_name -> feather.v1.GetFeaturesResponse.EntitiesEntry
	5,  // 1: feather.v1.EntityFeaturesResponse.features:type_name -> feather.v1.EntityFeatures
	13, // 2: feather.v1.EntityFeatures.features:type_name -> feather.v1.EntityFeatures.FeaturesEntry
	7,  // 3: feather.v1.FeatureValue.vector_value:type_name -> feather.v1.VectorValue
	14, // 4: feather.v1.PutFeaturesRequest.features:type_name -> feather.v1.PutFeaturesRequest.FeaturesEntry
	0,  // 5: feather.v1.HealthCheckResponse.status:type_name -> feather.v1.HealthCheckResponse.ServingStatus
	5,  // 6: feather.v1.GetFeaturesResponse.EntitiesEntry.value:type_name -> feather.v1.EntityFeatures
	6,  // 7: feather.v1.EntityFeatures.FeaturesEntry.value:type_name -> feather.v1.FeatureValue
	6,  // 8: feather.v1.PutFeaturesRequest.FeaturesEntry.value:type_name -> feather.v1.FeatureValue
	1,  // 9: feather.v1.FeatureService.GetFeatures:input_type -> feather.v1.GetFeaturesRequest
	1,  // 10: feather.v1.FeatureService.GetFeaturesStream:input_type -> feather.v1.GetFeaturesRequest
	2,  // 11: feather.v1.FeatureService.GetFeaturesAsOf:input_type -> feather.v1.GetFeaturesAsOfRequest
	8,  // 12: feather.v1.FeatureService.PutFeatures:input_type -> feather.v1.PutFeaturesRequest
	10, // 13: feather.v1.Health.Check:input_type -> feather.v1.HealthCheckRequest
	10, // 14: feather.v1.Health.Watch:input_type -> feather.v1.HealthCheckRequest
	3,  // 15: feather.v1.FeatureService.GetFeatures:output_type -> feather.v1.GetFeaturesResponse
	4,  // 16: feather.v1.FeatureService.GetFeaturesStream:output_type -> feather.v1.EntityFeaturesResponse
	3,  // 17: feather.v1.FeatureService.GetFeaturesAsOf:output_type -> feather.v1.GetFeaturesResponse
	9,  // 18: feather.v1.FeatureService.PutFeatures:output_type -> feather.v1.PutFeaturesResponse
	11, // 19: feather.v1.Health.Check:output_type -> feather.v1.HealthCheckResponse
	11, // 20: feather.v1.Health.Watch:output_type -> feather.v1.HealthCheckResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_feather_proto_init() }
func file_api_proto_feather_proto_init() {
	if File_api_proto_feather_proto != nil {
		return
	}
	file_api_proto_feather_proto_msgTypes[5].OneofWrappers = []any{
		(*FeatureValue_IntValue)(nil),
		(*FeatureValue_DoubleValue)(nil),
		(*FeatureValue_StringValue)(nil),
		(*FeatureValue_BoolValue)(nil),
		(*FeatureValue_BytesValue)(nil),
		(*FeatureValue_VectorValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_feather_proto_rawDesc), len(file_api_proto_feather_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_feather_proto_goTypes,
		DependencyIndexes: file_api_proto_feather_proto_depIdxs,
		EnumInfos:         file_api_proto_feather_proto_enumTypes,
		MessageInfos:      file_api_proto_feather_proto_msgTypes,
	}.Build()
	File_api_proto_feather_proto = out.File
	file_api_proto_feather_proto_goTypes = nil
	file_api_proto_feather_proto_depIdxs = nil
}
