apiVersion: v1
kind: Service
metadata:
  name: feather
  namespace: feather-system
  labels:
    app.kubernetes.io/name: feather
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: 50051
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: feather
---
apiVersion: v1
kind: Service
metadata:
  name: feather-headless
  namespace: feather-system
  labels:
    app.kubernetes.io/name: feather
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: 50051
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: feather
