package gitopsdefs

import (
	"fmt"
	"strings"
)

// upperFirst returns s with its first character uppercased.
func upperFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// CICDConfig configures CI/CD template generation.
type CICDConfig struct {
	Provider     string // "github", "gitlab", "generic"
	Branch       string
	FeatureDir   string
	FeatherImage string
	AutoApply    bool
}

// GenerateCICD generates a CI/CD pipeline template for the given provider.
func GenerateCICD(cfg CICDConfig) (string, error) {
	if cfg.Branch == "" {
		cfg.Branch = "main"
	}
	if cfg.FeatureDir == "" {
		cfg.FeatureDir = "features/"
	}
	if cfg.FeatherImage == "" {
		cfg.FeatherImage = "feather-store/feather:latest"
	}

	switch cfg.Provider {
	case "github":
		return GenerateGitHubActions(cfg), nil
	case "gitlab":
		return GenerateGitLabCI(cfg), nil
	case "generic":
		return generateGenericCI(cfg), nil
	default:
		return "", fmt.Errorf("unsupported CI/CD provider %q (supported: github, gitlab, generic)", cfg.Provider)
	}
}

// GenerateGitHubActions generates a GitHub Actions workflow YAML.
func GenerateGitHubActions(cfg CICDConfig) string {
	applyStep := "plan"
	if cfg.AutoApply {
		applyStep = "apply"
	}

	var sb strings.Builder
	sb.WriteString("# Generated by Feather GitOps\n")
	sb.WriteString("name: Feather Feature Store\n\n")
	sb.WriteString("on:\n")
	sb.WriteString("  push:\n")
	sb.WriteString(fmt.Sprintf("    branches: [%s]\n", cfg.Branch))
	sb.WriteString("    paths:\n")
	sb.WriteString(fmt.Sprintf("      - '%s**'\n", cfg.FeatureDir))
	sb.WriteString("  pull_request:\n")
	sb.WriteString(fmt.Sprintf("    branches: [%s]\n", cfg.Branch))
	sb.WriteString("    paths:\n")
	sb.WriteString(fmt.Sprintf("      - '%s**'\n\n", cfg.FeatureDir))
	sb.WriteString("jobs:\n")
	sb.WriteString("  feather-plan:\n")
	sb.WriteString("    runs-on: ubuntu-latest\n")
	sb.WriteString("    if: github.event_name == 'pull_request'\n")
	sb.WriteString("    steps:\n")
	sb.WriteString("      - uses: actions/checkout@v4\n")
	sb.WriteString("      - name: Feather Plan\n")
	sb.WriteString(fmt.Sprintf("        run: feather plan --dir %s\n", cfg.FeatureDir))
	sb.WriteString("        env:\n")
	sb.WriteString("          FEATHER_URL: ${{ secrets.FEATHER_URL }}\n\n")
	sb.WriteString("  feather-apply:\n")
	sb.WriteString("    runs-on: ubuntu-latest\n")
	sb.WriteString(fmt.Sprintf("    if: github.event_name == 'push' && github.ref == 'refs/heads/%s'\n", cfg.Branch))
	sb.WriteString("    steps:\n")
	sb.WriteString("      - uses: actions/checkout@v4\n")
	sb.WriteString(fmt.Sprintf("      - name: Feather %s\n", upperFirst(applyStep)))
	sb.WriteString(fmt.Sprintf("        run: feather %s --dir %s\n", applyStep, cfg.FeatureDir))
	sb.WriteString("        env:\n")
	sb.WriteString("          FEATHER_URL: ${{ secrets.FEATHER_URL }}\n")

	return sb.String()
}

// GenerateGitLabCI generates a GitLab CI pipeline YAML.
func GenerateGitLabCI(cfg CICDConfig) string {
	applyStep := "plan"
	if cfg.AutoApply {
		applyStep = "apply"
	}

	var sb strings.Builder
	sb.WriteString("# Generated by Feather GitOps\n")
	sb.WriteString(fmt.Sprintf("image: %s\n\n", cfg.FeatherImage))
	sb.WriteString("stages:\n")
	sb.WriteString("  - validate\n")
	sb.WriteString("  - deploy\n\n")
	sb.WriteString("variables:\n")
	sb.WriteString("  FEATHER_URL: ${FEATHER_URL}\n\n")
	sb.WriteString("feather-plan:\n")
	sb.WriteString("  stage: validate\n")
	sb.WriteString("  script:\n")
	sb.WriteString(fmt.Sprintf("    - feather plan --dir %s\n", cfg.FeatureDir))
	sb.WriteString("  rules:\n")
	sb.WriteString("    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'\n")
	sb.WriteString("      changes:\n")
	sb.WriteString(fmt.Sprintf("        - %s**/*\n\n", cfg.FeatureDir))
	sb.WriteString("feather-apply:\n")
	sb.WriteString("  stage: deploy\n")
	sb.WriteString("  script:\n")
	sb.WriteString(fmt.Sprintf("    - feather %s --dir %s\n", applyStep, cfg.FeatureDir))
	sb.WriteString("  rules:\n")
	sb.WriteString(fmt.Sprintf("    - if: $CI_COMMIT_BRANCH == '%s'\n", cfg.Branch))
	sb.WriteString("      changes:\n")
	sb.WriteString(fmt.Sprintf("        - %s**/*\n", cfg.FeatureDir))

	return sb.String()
}

// generateGenericCI generates a generic shell script for CI/CD.
func generateGenericCI(cfg CICDConfig) string {
	applyStep := "plan"
	if cfg.AutoApply {
		applyStep = "apply"
	}

	var sb strings.Builder
	sb.WriteString("#!/usr/bin/env bash\n")
	sb.WriteString("# Generated by Feather GitOps\n")
	sb.WriteString("set -euo pipefail\n\n")
	sb.WriteString(fmt.Sprintf("FEATURE_DIR=\"%s\"\n", cfg.FeatureDir))
	sb.WriteString(fmt.Sprintf("FEATHER_IMAGE=\"%s\"\n\n", cfg.FeatherImage))
	sb.WriteString("echo \"==> Validating feature definitions...\"\n")
	sb.WriteString("feather validate --dir \"${FEATURE_DIR}\"\n\n")
	sb.WriteString("echo \"==> Running feather plan...\"\n")
	sb.WriteString("feather plan --dir \"${FEATURE_DIR}\"\n\n")
	sb.WriteString(fmt.Sprintf("echo \"==> Running feather %s...\"\n", applyStep))
	sb.WriteString(fmt.Sprintf("feather %s --dir \"${FEATURE_DIR}\"\n\n", applyStep))
	sb.WriteString("echo \"==> Done.\"\n")

	return sb.String()
}
